#!/bin/bash

var1=-50
if [ $1 -eq 1 ]; then
	var1=50
fi
var1=$(($var1 + $(cat /sys/class/backlight/intel_backlight/brightness)))
if [ $var1 -lt 1 ]; then
	var1=1
fi
echo $var1 > /sys/class/backlight/intel_backlight/brightness 

